services:
  build-static:
    build: .
    command: >
      zig build size_check -DLibrary_Type=Static -DOptimization=ReleaseSmall -DCompile_Target=STM32F407
    volumes:
      - .:/app
    working_dir: /app

  build-shared:
    build: .
    command: >
      zig build size_check -DLibrary_Type=Shared -DOptimization=ReleaseFast -DCompile_Target=testing
    volumes:
      - .:/app
    working_dir: /app

  test:
    build: .
    command: >
      zig build test -DLibrary_Type=Shared -DOptimization=ReleaseFast -DCompile_Target=testing
    volumes:
      - .:/app
    working_dir: /app

  cdb:
    build: .
    command: >
      zig build cdb -DLibrary_Type=Shared -DOptimization=ReleaseFast -DCompile_Target=M0 -freference-trace
    volumes:
      - .:/app
    working_dir: /app
