services:
  build-static:
    build: .
    command: >
      zig build -DLibrary_Type=Static -DOptimization=ReleaseFast -DCompile_Target=M0
    volumes:
      - .:/app
    working_dir: /app

  build-shared:
    build: .
    command: >
      zig build -DLibrary_Type=Shared -DOptimization=ReleaseFast -DCompile_Target=M0
    volumes:
      - .:/app
    working_dir: /app

  test:
    build: .
    command: >
      zig test tests/All_test.zig -lc -lA-RTOS-M -I./inc -L./zig-out/lib/ 2>&1|cat
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - build-shared

  cdb:
    build: .
    command: >
      zig build cdb -DLibrary_Type=Shared -DOptimization=ReleaseFast -DCompile_Target=M0 -freference-trace
    volumes:
      - .:/app
    working_dir: /app

  linker:
    build: .
    command: >
      zig zig build-exe tools/LinkerGenerator.zig -O ReleaseFast -o generate_linker_script && ./generate_linker_script STM32F103 examples/Pic18f4550/linker.ld
    volumes:
      - .:/app
    working_dir: /app
