services:
  test:
    build: .
    command: >
      zig build -DLibrary_Type=Shared -Doptimize=ReleaseFast -DCompile_Target=testing test
    volumes:
      - .:/app
    working_dir: /app

  cdb:
    build: .
    command: >
      zig build -DLibrary_Type=Shared -Doptimize=ReleaseFast -DCompile_Target=testing cdb
    volumes:
      - .:/app
    working_dir: /app
