name: Build

on:
  push:
    branches: [main, zig-master]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build
        run: zig build -DCompile_Target=testing -DOptimization=ReleaseFast -DLibrary_Type=Static

      - name: Testing
        run: zig build test -DCompile_Target=testing -DOptimization=ReleaseFast -DLibrary_Type=Static

      - name: Build pkghash tool
        run: zig build pkghash -DCompile_Target=testing -DOptimization=ReleaseFast -DLibrary_Type=Static

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tag.outputs.version }} # Remove 'refs/tags/' from the tag name
          body_path: relnotes.md
          prerelease: true
