name: Publish Conan Recipe 

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      PACKAGE_NAME: "compos"
      PACKAGE_VERSION: "1.0.0"
      CONAN_USERNAME: "OmarSiwy"
      CONAN_CHANNEL: "stable" 
      CONAN_REMOTE_NAME: "github"
      CONAN_REMOTE_URL: "https://conan.pkg.github.com/${{ github.repository_owner }}"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Python and Conan
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: base
          auto-update-conda: true
          python-version: "3.8"
      
      - name: Install Conan
        run: |
          pip install conan==2.0.4

      - name: Set up Conan remote and authentication for GitHub Packages
        run: |
          conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_URL --force
          conan user -p $GITHUB_TOKEN -r $CONAN_REMOTE_NAME $CONAN_USERNAME

      - name: Upload Conan package to GitHub Packages
        if: startsWith(github.ref, 'refs/tags')
        run: |
          conan upload "${PACKAGE_NAME}/${PACKAGE_VERSION}@${CONAN_USERNAME}/${CONAN_CHANNEL}" --all -r $CONAN_REMOTE_NAME --confirm
