name: Publish Conan Recipe

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      PACKAGE_NAME: "compos"
      PACKAGE_VERSION: "1.0.0"
      CONAN_USERNAME: "omarsiwy"
      CONAN_CHANNEL: "stable"
      CONAN_REMOTE_NAME: "github"
      CONAN_REMOTE_URL: "https://conan.pkg.github.com/OmarSiwy"
      CONAN_LOGIN_USERNAME: "OmarSiwy"
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Conan
        run: |
          pip install conan==2.0.4

      - name: Configure Conan for GitHub Packages
        run: |
          conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_URL --force
          # Authentication is handled via environment variables in Conan 2.x

      - name: Export Conan Recipe
        run: |
          conan export . --name=$PACKAGE_NAME --version=$PACKAGE_VERSION --user=$CONAN_USERNAME --channel=$CONAN_CHANNEL

      - name: Upload Conan Recipe to GitHub Packages
        if: startsWith(github.ref, 'refs/tags')
        run: |
          conan upload "${PACKAGE_NAME}/${PACKAGE_VERSION}@${CONAN_USERNAME}/${CONAN_CHANNEL}" -r $CONAN_REMOTE_NAME --confirm --only-recipe
